// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeG0xhytIGQgbF94LVvo7dzyrd5X9K3Kk',
    appId: '1:721104807316:web:d94bfad96a941168a0db81',
    messagingSenderId: '721104807316',
    projectId: 'thewall-b63e1',
    authDomain: 'thewall-b63e1.firebaseapp.com',
    storageBucket: 'thewall-b63e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv2VcYJ7THQP__mkp42TtPESMrFOdwcU0',
    appId: '1:721104807316:android:2de766d8b89d3c7ba0db81',
    messagingSenderId: '721104807316',
    projectId: 'thewall-b63e1',
    storageBucket: 'thewall-b63e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT83Ar-6q-_7po8iWLkz6ohdCzA2rOSYQ',
    appId: '1:721104807316:ios:bb2a93dd7d26a0f7a0db81',
    messagingSenderId: '721104807316',
    projectId: 'thewall-b63e1',
    storageBucket: 'thewall-b63e1.appspot.com',
    iosClientId: '721104807316-qakua9ekqehhhc4tk5nm2pmm4g6pa3m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT83Ar-6q-_7po8iWLkz6ohdCzA2rOSYQ',
    appId: '1:721104807316:ios:79da8b336c0bb0fba0db81',
    messagingSenderId: '721104807316',
    projectId: 'thewall-b63e1',
    storageBucket: 'thewall-b63e1.appspot.com',
    iosClientId: '721104807316-ie4u4i2efg5v1l21mvptcjob466k5qru.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWall.RunnerTests',
  );
}
